# General options

device: cpu
mode: experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
precision: double

# network options

# optimizer: optimizer for the network
optimizer:
  - Adam

# loss: loss function for the network
loss:
  - CrossEntropyLoss

batch_size:
  - 32
learning_rate:
  - 0.01
epochs:
  - 100

early_stopping:
  enabled:
    False
  patience:
    30

# how to sample the training data
training_data_sampling: { type: 'default' } # undersampling, oversampling, default
#training_data_sampling: { type: 'default' } # undersampling, oversampling, default

#input_features: {name: constant, value: 1.0, random_variation: { mean: 0.0, variance: 0.5 }}
input_features: {name: node_labels, transformation: 'one_hot'}

save_best_model: True
#best_model: True
